-- Historique de chat (équivalent n8n) — idempotent si la table existe déjà
-- node scripts/db-exec.cjs migrations/20260424120000_n8n_chat_histories_v6.sql

CREATE TABLE IF NOT EXISTS public.n8n_chat_histories_v6 (
  id int8 GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1
    NO CYCLE
  ) NOT NULL,
  session_id varchar(255) NOT NULL,
  message jsonb NOT NULL,
  CONSTRAINT n8n_chat_histories_v6_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_n8n_chat_histories_v6_session
  ON public.n8n_chat_histories_v6 (session_id);
