-- Schéma aligné sur l’existant (clés, types, noms de contraintes).
-- Exécution : psql -v ON_ERROR_STOP=1 "$DATABASE_URL" -f migrations/20260423120000_puissance_irradiance_production_vente.sql

CREATE TABLE public.puissance_installee (
  site_name character varying(255) NOT NULL,
  puissance_installee double precision NOT NULL,
  unite character varying(50) NOT NULL,
  CONSTRAINT puissance_installee_pkey PRIMARY KEY (site_name)
);

CREATE TABLE public.irradiance (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  time_of_measure timestamp without time zone NOT NULL,
  temp_ambiante double precision,
  temp_module double precision,
  irradiance double precision,
  site_name character varying(255) NOT NULL,
  CONSTRAINT irradiance_pkey PRIMARY KEY (id),
  CONSTRAINT fk_irradiance_site FOREIGN KEY (site_name) REFERENCES public.puissance_installee (site_name)
);

CREATE TABLE public.production (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  time_of_measure timestamp without time zone NOT NULL,
  equipement character varying(255),
  puissance_active double precision,
  puissance_reactive double precision,
  puissance_apparente double precision,
  cosphi double precision,
  intensite1 double precision,
  intensite2 double precision,
  intensite3 double precision,
  courant_nominal double precision,
  frequence double precision,
  tensionv1 double precision,
  tensionv2 double precision,
  tensionv3 double precision,
  tension12 double precision,
  tension23 double precision,
  tension31 double precision,
  site_name character varying(255) NOT NULL,
  CONSTRAINT production_pkey1 PRIMARY KEY (id),
  CONSTRAINT fk_production_site FOREIGN KEY (site_name) REFERENCES public.puissance_installee (site_name)
);

CREATE SEQUENCE public.vente_id_seq;

CREATE TABLE public.vente_carburant (
  id integer NOT NULL DEFAULT nextval('public.vente_id_seq'::regclass),
  date_vente date NOT NULL,
  station character varying(100) NOT NULL,
  product_name character varying(50) NOT NULL,
  volume numeric NOT NULL,
  unite character varying(10) NOT NULL,
  CONSTRAINT vente_pkey PRIMARY KEY (id)
);

ALTER SEQUENCE public.vente_id_seq OWNED BY public.vente_carburant.id;
